#NUMPY IN PYHTON

#What is numpy
NumPy (Numerical Python) is a Python library used for fast numerical and mathematical computations.
It provides support for:
-Large multi-dimensional arrays
-Matrices
-Many mathematical, statistical, and linear algebra functions

#Why numPy over pyhton Lists?
NumPy arrays are preferred over Python lists because they are faster, memory-efficient, and 
more powerful for numerical operations.

#📌 NumPy Use Cases in Data Science & Machine Learning
-Representing datasets as arrays
-Matrix operations in algorithms
-Gradient calculations
-Linear regression and logistic regression math
-Basis for libraries like Pandas, Scikit-learn, TensorFlow, PyTorch

In [3]:
#Installing numpy
pip install numpy
#importing numpy
import numpy as np

In [4]:
np.__version__

'1.24.3'

In [6]:
#Creating a numpy array
#type - 1
a1 = [23, 45, 18, 88]
n1 = np.array(a1)
print(n1)
#type - 2
n2 = np.array([12, 25, 15, 70])
print(n2)

[23 45 18 88]
[12 25 15 70]


In [8]:
#numpy array attributes
print(n2.ndim)  #dimension of numpy array
print(n2.shape) #shape of numpy array
print(n2.size) #size of numpy array
print(n2.dtype) #Data  type of numpy array
print(n2.itemsize) #Itemsize of numpy array

1
(4,)
4
int32
4


#Built-in Array Creation Functions
zeros()
ones()
full()
arange()
linspace()
eye()
random.rand()
random.randint()
These are all other ways of creating numpy arrays

In [13]:
zeros_array = np.zeros((2, 3))
print("zeros array: ",zeros_array)
ones_array = np.ones((3, 3))
print("ones array: ", ones_array)
constant_array = np.full((3, 2), 3)
print("constant array: ", constant_array)
range_array = np.arange(0, 10, 2)
print("range array: ", range_array)
linspace_array = np.linspace(0,1, 5)
print("linspace array: ", linspace_array)


zeros array:  [[0. 0. 0.]
 [0. 0. 0.]]
ones array:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
constant array:  [[3 3]
 [3 3]
 [3 3]]
range array:  [0 2 4 6 8]
linspace array:  [0.   0.25 0.5  0.75 1.  ]


In [26]:
random_array = np.random.rand(2, 3)
print(random_array)
normal_array = np.random.randn(2, 2)
print(normal_array)
randint_array = np.random.randint(2, 10, size = (3,3))
print(randint_array)


[[0.9980604  0.73774711 0.68356142]
 [0.63236638 0.18615022 0.88601629]]
[[ 0.5424112   0.67000768]
 [-0.69515109 -1.2140628 ]]
[[6 3 4]
 [4 3 5]
 [5 2 7]]


#INDEXING IN NumPy array

In [17]:
#Indexing in one dimensional array
ar = np.array([34, 56, 12, 77, 45])
print(ar[3])
print(ar[0])

77
34


In [19]:
#Indexing in one dimensional array
mat = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(mat[1, 2])
print(2, 1)

6
2 1


In [21]:
cube = np.array([[[1, 2, 3],
                [8, 2, 0],
                 [4, 6, 1]],
                [[4, 1, 5],
                 [1, 0, 1],
                 [5, 2, 3]]])
print(cube[1, 2, 0])
print(cube[0, 1, 2])

5
0


In [24]:
#fancy indexing
mat = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
lst = [1, 0]
print(mat[lst])

[[4 5 6]
 [1 2 3]]


In [27]:
#integer indexing
print(mat[0, 2])

3


In [28]:
#Boolean indexing
print(mat[mat > 5])

[6 7 8 9]


#SLICING IN NumPy array

In [32]:
#2D array slicing
mat = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(mat[[0, 2]]) #first and last row
print(mat[[1]]) #middle row

[[1 2 3]
 [7 8 9]]
[[4 5 6]]


In [33]:
# 3d array slicing
n_arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]], [[50, 65, 8], [70, 85, 10], [11, 22, 33]]])
print("Array:")
print(n_arr)

res_arr = n_arr[:,[1]] #aceesing middle row 
print("Accessed Rows:")
print(res_arr)

Array:
[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]]
Accessed Rows:
[[[30 45 55]]

 [[70 85 10]]]


#Reshape NumPy Array - Python

In [34]:
a = np.array([23, 1, 56, 19])
print(a.reshape(2,2))

[[23  1]
 [56 19]]


In [35]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a1.reshape(2, 2, 2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
a2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a2.reshape(3, -1)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#Resizing numpy array in python

In [37]:
#Example 1
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)

[[1 2 3]
 [4 5 6]]


In [38]:
#Example 2
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))
print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [41]:
#Example 3
arr = np.array([10, 20, 30, 40, 50])
arr.resize((2, 2))
print(arr)

[[10 20]
 [30 40]]


#nNUMPY ARTHEMATIC OPERATIONS

In [44]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.add(a, b)
print(res)
res = np.subtract(a, b)
print(res)
res = np.multiply(a, b)
print(res)
res = np.divide(a, b)
print(res)
res = np.mod(a, b)
print(res)
res = np.power(a, b)
print(res)


[  7  77  23 130]
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[ 1  2  3 10]
[        25 1934917632  419538377          0]


#UNIVERSAL NUMPY FUNCTIONS

In [45]:
#Trigonometric functions
import numpy as np

angles = np.array([0, 30, 45, 60, 90]) 
rad = np.deg2rad(angles)  # convert degrees to radians

# Sine of angles
sin_vals = np.sin(rad)
print("Sine values:", sin_vals)

# Inverse sine in degrees
inv_sin = np.rad2deg(np.arcsin(sin_vals))
print("Inverse sine (degrees):", inv_sin)

# Hyperbolic sine
sinh_vals = np.sinh(rad)
print("Hyperbolic sine:", sinh_vals)

# Hypotenuse of a right triangle
hyp = np.hypot(3, 4)
print("Hypotenuse:", hyp)

Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Inverse sine (degrees): [ 0. 30. 45. 60. 90.]
Hyperbolic sine: [0.         0.54785347 0.86867096 1.24936705 2.3012989 ]
Hypotenuse: 5.0


In [46]:
#stastical functions
import numpy as np

weights = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

# Min and Max
print("Min and Max:", np.amin(weights), np.amax(weights))

# Range
print("Range:", np.ptp(weights))

# 70th Percentile
print("70th Percentile:", np.percentile(weights, 70))

# Mean
print("Mean:", np.mean(weights))

# Median
print("Median:", np.median(weights))

# Standard Deviation
print("Std Dev:", np.std(weights))

# Variance
print("Variance:", np.var(weights))

# Average
print("Average:", np.average(weights))

Min and Max: 45.0 73.25
Range: 28.25
70th Percentile: 55.317
Mean: 54.3225
Median: 51.6
Std Dev: 8.052773978574091
Variance: 64.84716875
Average: 54.3225


In [48]:
#bitwise functions
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd  = np.array([1, 3, 5, 7, 9, 17, 33])

# Bitwise AND, OR, XOR
print("AND:", np.bitwise_and(even, odd))
print("OR :", np.bitwise_or(even, odd))
print("XOR:", np.bitwise_xor(even, odd))

# Bitwise NOT
print("Invert:", np.invert(even))

# Bit shifts
print("Left shift :", np.left_shift(even, 1))
print("Right shift:", np.right_shift(even, 1))

AND: [ 0  2  4  6  8 16 32]
OR : [ 1  3  5  7  9 17 33]
XOR: [1 1 1 1 1 1 1]
Invert: [ -1  -3  -5  -7  -9 -17 -33]
Left shift : [ 0  4  8 12 16 32 64]
Right shift: [ 0  1  2  3  4  8 16]


#NUMPY STACKING IN PYTHON

In [2]:
#1D array
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b), axis=0)
print(res)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))
print(np.stack((a, b), axis=-1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [4]:
#2D array
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([[7, 8, 9],
              [10, 11, 12]])

print(np.stack((x, y), axis=0))
print(np.stack((x, y), axis=1))
print(np.stack((x, y), axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


#NUMPY SPILTING IN PYTHON

In [11]:
#1D array
ar = np.arange(6)
res = np.split(ar, 2)
print(res)

[array([0, 1, 2]), array([3, 4, 5])]


In [12]:
arr = np.array([1, 2, 3, 4,5 ,6 ,7 ,8])
res = np.array_split(arr, 4)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [13]:
#2D array
array = np.array([[1, 2,3],
                 [4,5,6],
                 [7,8,9]])
res = np.split(array, 3, axis=1)
print(res)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [16]:
#Horizontal split
array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Horizontal splitting into 2 subarrays along axis=1
result = np.hsplit(array, 2)

print("2D Array:")
print(array)
print("\nResult after numpy.hsplit():")
print(result)

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after numpy.hsplit():
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [25]:
#vertical splitting
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])
res = np.vsplit(matrix, 2)
print(res)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


#NumPy Array Broadcasting

Broadcasting in NumPy allows us to perform arithmetic operations on arrays ofdifferent shapes 
without reshaping them.

In [26]:
#example 1
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
x = 10
print(a + x)

[[11 12 13]
 [14 15 16]]


In [27]:
#example 2
a1 = np.array([[3, 1, 7],
              [6,9,2]])
a2 = np.array([4,0,3])
rse = a1 + a2
print(rse)

[[ 7  1 10]
 [10  9  5]]


In [28]:
#example 3
a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["Adult", "Minor"])
res = np.where(a > 18, b[0], b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


In [30]:
#example 4
mat = np.array([[1, 5, 3], [8, 6, 7]])
mat2 = np.array([3, 0, 1])
res = mat * mat2
print(res)

[[ 3  0  3]
 [24  0  7]]
