# Day 5 – NumPy Matrix Operations for Machine Learning

### 🎯 Goal
To understand matrix multiplication, matrix and vector products, determinant and inverse of matrices, and inner and outer products using NumPy, which are fundamental for Machine Learning and Linear Algebra.


#MATRIX MANIPULATION AND MULTIPLICATION IN PYTHON

In [3]:
#Element wise addition, subtraction, and division
import numpy as np
x = np.array([[1,5,7], [6, 2, 5]])
y = np.array([[3, 1, 2], [6, 9, 4]])
print(np.add(x, y))
print(np.subtract(x, y))
print(np.divide(x, y))

[[ 4  6  9]
 [12 11  9]]
[[-2  4  5]
 [ 0 -7  1]]
[[0.33333333 5.         3.5       ]
 [1.         0.22222222 1.25      ]]


In [5]:
#Element wise  multiplications vs matrix multiplication
x = np.array([[1,5], [6, 2]])
y = np.array([[3, 1], [6, 9]])
print(np.multiply(x, y)) #element wise multiplication
print(np.dot(x, y))

[[ 3  5]
 [36 18]]
[[33 46]
 [30 24]]


In [6]:
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis=0))
print("Row-wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements: 34
Column-wise sum: [16 18]
Row-wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]


#PRODUCTS OF VECTORS AND MATRICES IN NUMPY

In [7]:
#inner product
# Define vectors
a = np.array([2, 6])
b = np.array([3, 10])

print("Inner product of vectors a and b =")
print(np.inner(a, b))

# Define matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner product of matrices x and y =")
print(np.inner(x, y))

Inner product of vectors a and b =
66
Inner product of matrices x and y =
[[17 52]
 [13 62]]


In [8]:
#Outer product
# Define vectors
a = np.array([2, 6])
b = np.array([3, 10])

print("Outer product of vectors a and b =")
print(np.outer(a, b))

# Define matrices
x = np.array([[3, 6, 4], [9, 4, 6]])
y = np.array([[1, 15, 7], [3, 10, 8]])

print("Outer product of matrices x and y =")
print(np.outer(x, y))

Outer product of vectors a and b =
[[ 6 20]
 [18 60]]
Outer product of matrices x and y =
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


In [9]:
#Cross product
# Define vectors as 3D (z=0 for 2D compatibility)
a = np.array([3, 6, 0])
b = np.array([9, 10, 0])

print("Cross product of vectors a and b =")
print(np.cross(a, b))

# Define matrices (already 3D rows)
x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])

print("Cross product of matrices x and y =")
print(np.cross(x, y))

Cross product of vectors a and b =
[  0   0 -24]
Cross product of matrices x and y =
[[ -9  51 -32]
 [-15   3   3]]


In [10]:
#Finding determinent of a mtrix
A = np.array([[5, 3], [6, 9]])
sign, logdet = np.linalg.slogdet(A)
result = sign * np.exp(logdet)
print(result)

27.0


In [11]:
#Finding the inverse of a matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


#📌 Handling Missing Values in NumPy

In [16]:
A = np.array([12, 7, 25, np.nan, 90, 69, 72, np.nan, 37])
print(A)
#checking the missing values 
b = np.isnan(A)
print(b)
#counting the missing values
print(np.sum(b))

[12.  7. 25. nan 90. 69. 72. nan 37.]
[False False False  True False False False  True False]
2


In [19]:
#cleaning the data
cleaned = A[~np.isnan(A)]
print(cleaned)

[12.  7. 25. 90. 69. 72. 37.]


In [20]:
#replacing missing values with constant values
c = np.nan_to_num(A, nan=0)
print(c)

[12.  7. 25.  0. 90. 69. 72.  0. 37.]


In [22]:
#replacing missing values with mean, median and standard deviation
mean_val = np.nanmean(A)
filled = np.nan_to_num(A, nan=mean_val)
print(filled)

[12.          7.         25.         44.57142857 90.         69.
 72.         44.57142857 37.        ]


In [23]:
median_val = np.nanmedian(A)
filled = np.nan_to_num(A, nan=median_val)
print(filled)

[12.  7. 25. 37. 90. 69. 72. 37. 37.]


In [24]:
std_val = np.nanstd(A)
filled = np.nan_to_num(A, nan=std_val)
print(filled)

[12.          7.         25.         30.06116214 90.         69.
 72.         30.06116214 37.        ]


In [26]:
#Problem 1
"""write a Python program that prints odd numbers from 1 to 30 using the
NumPy array. Also, print the data type of output."""
arr = np.arange(1, 31)
odd_mask = arr % 2 != 0
res = arr[odd_mask]
print(res)
print(res.dtype)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
int32


In [27]:
#probelm 2
"""Write a Python program to declare a list and NumPy arrays(1-D, 2-D, and
3-D) and compare the size of the list and the arrays. Also, compare the
size of each element in the list and the arrays (in terms of memory
occupancy). """
import numpy as np
import sys

# Declare a Python list
py_list = [1, 2, 3, 4, 5]

# Declare NumPy arrays
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Display total memory size
print("Total Memory Size:")
print("Python List:", sys.getsizeof(py_list), "bytes")
print("NumPy 1-D Array:", arr_1d.nbytes, "bytes")
print("NumPy 2-D Array:", arr_2d.nbytes, "bytes")
print("NumPy 3-D Array:", arr_3d.nbytes, "bytes")

print("\nSize of Each Element:")
print("Python List Element:", sys.getsizeof(py_list[0]), "bytes")
print("NumPy Array Element:", arr_1d.itemsize, "bytes")

30
